ignored = [
  "github.com/turbinelabs/nonstdlib*",
  "github.com/turbinelabs/test*",
  "github.com/golang/mock/*",
  "golang.org/x/net",
]

[[constraint]]
  name = "github.com/ghodss/yaml"
  revision = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7"
