ignored = [
  "github.com/turbinelabs/nonstdlib*",
  "github.com/turbinelabs/test*",
  "github.com/golang/mock/*"
]

[[constraint]]
  name = "github.com/ghodss/yaml"
  revision = "04f313413ffd65ce25f2541bfd2b2ceec5c0908c"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "a3f3340b5840cee44f372bddb5880fcbc419b46a"

